# Generated by Django 3.2.5 on 2021-07-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210726_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ctegory',
            new_name='Category',
        ),
    ]
